export type DataSource = "ai" | "manual";
export type DataStatus = "imported" | "enriching" | "enriched" | "missing_contact" | "verified" | "duplicate" | "ready_for_outreach";
export type DataProvenance = {
  source: DataSource;
  provider: string;
  batch_code: string | null;
  original_filename: string | null;
  row_number: number | null;
  created_at: string;
  raw_payload?: unknown;
  status?: string;
};
export type DataRecord = {
  id: string;
  record_kind: "prospect" | "candidate";
  business_name: string;
  industry: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  phone: string | null;
  email: string | null;
  website_url: string | null;
  source: DataSource;
  provider: string;
  status: DataStatus;
  enrichment_status: string;
  enrichment_error: string | null;
  verified: boolean;
  ready_for_outreach: boolean;
  created_at: string;
  provenance: DataProvenance[];
};
export type DataDetail = DataRecord & {
  source_payload: unknown;
  lead_id: string | null;
  state_key: string | null;
  potential_duplicate_of_id: string | null;
};
export type DataImportResult = {
  batch_id: string;
  batch_code: string;
  replayed: boolean;
  counts: { total: number; imported: number; duplicate: number; invalid: number; missing_email: number; missing_phone: number };
  enrichment: { ready: number; enriched: number; failed: number };
  rows: Array<{ row_number: number; status: "imported" | "duplicate" | "invalid"; acquisition_prospect_id: string | null; errors: string[] }>;
};
export type DataBatch = {
  id: string;
  batch_code: string;
  original_filename: string;
  source_kind: DataSource;
  provider: string;
  total_rows: number;
  valid_rows: number;
  duplicate_rows: number;
  invalid_rows: number;
  missing_email_rows: number;
  missing_phone_rows: number;
  created_at: string;
  enrichment: { ready: number; enriched: number; failed: number };
};

export type DataProspect = {
  id: string;
  identity_key: string;
  acquisition_import_batch_id: string;
  source_row_number: number;
  normalized_business_name: string;
  normalized_address: string;
  normalized_city: string;
  normalized_state: string;
  normalized_zip: string;
  normalized_email: string | null;
  normalized_phone: string | null;
  domain: string | null;
  business_name: string;
  address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  website_url: string | null;
  industry: string | null;
  source_kind: DataSource;
  provider: string;
  source_payload: Record<string, unknown>;
  state_key: string;
  enrichment_status: "pending" | "enriching" | "enriched" | "no_match" | "failed";
  enrichment_error: string | null;
  enriched_at: string | null;
  verified_at: string | null;
  potential_duplicate_of_id: string | null;
  lead_id: string | null;
  created_at: string;
  updated_at: string;
};
